# Uncomment this line to define a global platform for your project
 platform :ios, '9.0'

target 'Tools' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
 use_frameworks!

pod ‘AFNetworking’
pod 'SDWebImage'
pod 'MJExtension'
pod 'MMDrawerController'

  # Pods for Tools

  target 'ToolsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ToolsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
